-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.30.0-pre.4ea06a20e98f9419a92a76b444985af00eb62b65"]
    minimum_pre_commit_version: '0'
