-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.28.0-pre.35e9ba866c2b3602ab7a8e814b82d1fdec0d57a1"]
    minimum_pre_commit_version: '0'
