-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.21.0-pre.2ed7800b5768e0f526bcf413287fe6339174fb2c"]
    minimum_pre_commit_version: '0'
