-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.26.0-pre.3bc9bcf32c7b8d403c265f679f09f64c05d31773"]
    minimum_pre_commit_version: '0'
