-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.12.0-pre.914ed2c676f81edc350253989d54f5a46d333796"]
    minimum_pre_commit_version: '0'
