-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.21.0-pre.1832bd975f0aea73b629b0411541b30fc35e9900"]
    minimum_pre_commit_version: '0'
