-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.23.0-pre.a11d0e8f8f8e5bbc745d9315086b97cbc49d2890"]
    minimum_pre_commit_version: '0'
