-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.30.0-pre.05ea91063c3b19345b58f4a659a3c56f16c395c2"]
    minimum_pre_commit_version: '0'
