-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.20.0-pre.03e6d84ee5182d7e547d9b09d2d121daedb7f7c3"]
    minimum_pre_commit_version: '0'
