-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.21.0-pre.8260c3e18ab31228424795549d72262ba5babee9"]
    minimum_pre_commit_version: '0'
