-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.27.0-pre.35c06cb877d74a3b56e41a1ea36ea0fbfec74c91"]
    minimum_pre_commit_version: '0'
