-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.13.0-pre.f9ee84a846bb7b7ee3de63e3bf29eb557a972efc"]
    minimum_pre_commit_version: '0'
