-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.26.0-pre.d77b3833b02e97a1420e85989a1f18e8011d547a"]
    minimum_pre_commit_version: '0'
