-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.17.0-pre.634eec72e16899813cd98bf766d83dfd0e374b1f"]
    minimum_pre_commit_version: '0'
