-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.20.0-pre.2d948df49a08b458bc6ecf2edc3c6c7c18977deb"]
    minimum_pre_commit_version: '0'
