-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.12.0-pre.7c87812bd57f9fbfd204b5f5fee04c5040806785"]
    minimum_pre_commit_version: '0'
