-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.13.1-pre.80e8402790c4112e64bda2dd9a42fa897ee4ab8b"]
    minimum_pre_commit_version: '0'
