-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.17.0-pre.ab207d26d0610ef7e4c2cf32cc9b12756adbff26"]
    minimum_pre_commit_version: '0'
