-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.21.0-pre.5c20a38611223a4fd816566de9abf6ed7f925d7c"]
    minimum_pre_commit_version: '0'
