-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.15.1-pre.74879e480e805b5a97f784bc494b075cf01232f4"]
    minimum_pre_commit_version: '0'
