-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.19.0-pre.560974e53ed36f3fb798ab6cfb847db567ff0e6c"]
    minimum_pre_commit_version: '0'
