-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.30.0-pre.6b1f66278446efd01cb3d0b61a5fca712725fefa"]
    minimum_pre_commit_version: '0'
