-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.25.0-pre.2b30557056d5d0b3c3ee91d376e546bed74fdb17"]
    minimum_pre_commit_version: '0'
