-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.22.0-pre.be090d09b6bdc2105e21c2f6de0cdcc9da657b50"]
    minimum_pre_commit_version: '0'
