-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.22.0-pre.73fd76138b53c7f3246c4f608ffb12fd0cc94a72"]
    minimum_pre_commit_version: '0'
