-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.33.0-pre.f3f9a6a7474e60ff90376a4d74be55d08014b2d3"]
    minimum_pre_commit_version: '0'
