-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.12.0-pre.b172db8a55c21ff8d7f8158cc894034fd9ee545e"]
    minimum_pre_commit_version: '0'
