-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.22.0-pre.3d0a5dcbd62437a9364a24d7fc5b3bc41b067525"]
    minimum_pre_commit_version: '0'
