-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.20.0-pre.6013c7a26589132b35acad2167ce5d81b18f7141"]
    minimum_pre_commit_version: '0'
