-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.25.0-pre.b1fa11d6062dc5008e4e263cf556695a64ae88ad"]
    minimum_pre_commit_version: '0'
