-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.27.0-pre.8307757deb9b70db4fda716d4a4afb7cef522dc9"]
    minimum_pre_commit_version: '0'
