-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.12.0-pre.55de9f6ade0e4d5bf366e697ae53df235a36a78d"]
    minimum_pre_commit_version: '0'
