-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.13.1-pre.fcb81a8b32dd37ccfdbb5de018ece93b92ce84bf"]
    minimum_pre_commit_version: '0'
