-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.24.0-pre.7db9baf1f6bcd400f94a778bcdb7061a7a0583e2"]
    minimum_pre_commit_version: '0'
