-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.29.0-pre.980c6e096c573aa6a7a2b541d176c9be56f31e4f"]
    minimum_pre_commit_version: '0'
