-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.14.0-pre.1fe89bd7355d48c99c35be7d4429b1095529dc7f"]
    minimum_pre_commit_version: '0'
