-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.31.0-pre.649f41ba65a9bb7f8c7d0c4a260ae9ddd773afb8"]
    minimum_pre_commit_version: '0'
