-   id: cdk8s
    name: cdk8s-cli
    description: 'Pre-commit hook for cdk8s'
    entry: cdk8s
    language: node
    'files': .*cdk8s\.ya?ml$
    args: []
    require_serial: false
    additional_dependencies: ["cdk8s-cli@0.20.0-pre.e12fac1835c64f57bd55feb56ec59aa8f648a598"]
    minimum_pre_commit_version: '0'
